name: Generate README

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/generate-readme.yml'
      - 'automation/**'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd automation
        pip install -r requirements.txt
        
    - name: Generate README
      env:
        GOOGLEAPIKEY: ${{ secrets.GOOGLEAPIKEY }}
      run: |
        cd automation
        python generate_readme.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README files" && git push) 